version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.1
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=demo
      - node.name=elasticsearch
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - demo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.1
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    networks:
      - demo
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  demo:
    driver: bridge

volumes:
  es_data: